import { Building, Edge, Node, Room } from "@/core/types";

export const nodes: Node[] = [
	{ id: "N_MAIN_GATE", x: 80, y: 260, label: "Main Gate" },
	{ id: "N_MAIN_JUNCTION", x: 180, y: 220, label: "Main Junction" },
	{ id: "N_APEX", x: 260, y: 120, label: "Apex Block" },
	{ id: "N_ESB", x: 360, y: 120, label: "ESB Block" },
	{ id: "N_DES", x: 460, y: 140, label: "DES Block" },
	{ id: "N_LHC", x: 320, y: 190, label: "LHC" },
	{ id: "N_ARCH", x: 520, y: 200, label: "Architecture" },
	{ id: "N_RND", x: 420, y: 80, label: "R&D Block" },
	{ id: "N_WORKSHOP", x: 220, y: 200, label: "Workshop" },
	{ id: "N_HERITAGE", x: 240, y: 260, label: "Heritage Block" },
	{ id: "N_SPORTS", x: 520, y: 260, label: "Sports & Fitness" },
	{ id: "N_BHASKARA", x: 160, y: 160, label: "Bhaskara Hostel" },
	{ id: "N_ARYABHATA", x: 420, y: 200, label: "Aryabhata Hostel" },
	{ id: "N_FRESHERS", x: 120, y: 120, label: "Freshers Block" },
	{ id: "N_NRI", x: 520, y: 120, label: "NRI Block" },
	{ id: "N_ADMIN", x: 200, y: 180, label: "Admin Block" },
	{ id: "N_LIBRARY", x: 340, y: 160, label: "Central Library" },
	{ id: "N_MULTIPURPOSE", x: 280, y: 240, label: "Multipurpose Block" },
	{ id: "N_HOSTEL_B", x: 80, y: 120, label: "Boys Hostel" },
	{ id: "N_HOSTEL_G", x: 80, y: 180, label: "Girls Hostel" },
];

export const edges: Edge[] = [
	{ from: "N_MAIN_GATE", to: "N_MAIN_JUNCTION", weight: 60, kind: "mainRoad" },
	{ from: "N_MAIN_JUNCTION", to: "N_APEX", weight: 70, kind: "mainRoad" },
	{ from: "N_MAIN_JUNCTION", to: "N_ADMIN", weight: 50, kind: "mainRoad" },
	{ from: "N_MAIN_JUNCTION", to: "N_BHASKARA", weight: 60, kind: "normal" },
	{ from: "N_MAIN_JUNCTION", to: "N_HERITAGE", weight: 80, kind: "normal" },
	{ from: "N_APEX", to: "N_ESB", weight: 60, kind: "normal" },
	{ from: "N_ESB", to: "N_DES", weight: 60, kind: "normal" },
	{ from: "N_ESB", to: "N_RND", weight: 55, kind: "normal" },
	{ from: "N_ESB", to: "N_LHC", weight: 50, kind: "normal" },
	{ from: "N_LHC", to: "N_LIBRARY", weight: 35, kind: "normal" },
	{ from: "N_LHC", to: "N_ARYABHATA", weight: 45, kind: "normal" },
	{ from: "N_ARYABHATA", to: "N_ARCH", weight: 50, kind: "normal" },
	{ from: "N_ADMIN", to: "N_WORKSHOP", weight: 40, kind: "normal" },
	{ from: "N_WORKSHOP", to: "N_APEX", weight: 50, kind: "normal" },
	{ from: "N_WORKSHOP", to: "N_LHC", weight: 45, kind: "normal" },
	{ from: "N_HERITAGE", to: "N_MULTIPURPOSE", weight: 40, kind: "normal" },
	{ from: "N_MULTIPURPOSE", to: "N_LHC", weight: 45, kind: "normal" },
	{ from: "N_MULTIPURPOSE", to: "N_SPORTS", weight: 70, kind: "mainRoad" },
	{ from: "N_HOSTEL_B", to: "N_FRESHERS", weight: 35, kind: "normal" },
	{ from: "N_FRESHERS", to: "N_BHASKARA", weight: 45, kind: "normal" },
	{ from: "N_HOSTEL_G", to: "N_MAIN_JUNCTION", weight: 50, kind: "normal" },
	{ from: "N_DES", to: "N_ARCH", weight: 60, kind: "normal" },
	{ from: "N_DES", to: "N_NRI", weight: 45, kind: "normal" },
	{ from: "N_NRI", to: "N_SPORTS", weight: 55, kind: "normal" },
	{ from: "N_SPORTS", to: "N_HERITAGE", weight: 85, kind: "mainRoad" },
];

export const buildings: Building[] = [
	{ id: "B_APEX", name: "Apex Block" },
	{ id: "B_ESB", name: "ESB Block" },
	{ id: "B_DES", name: "DES Block" },
	{ id: "B_LHC", name: "Lecture Hall Complex" },
	{ id: "B_ARCH", name: "Architecture Block" },
	{ id: "B_RND", name: "R&D Block" },
	{ id: "B_WORKSHOP", name: "Workshop Block" },
	{ id: "B_HERITAGE", name: "Heritage Block" },
	{ id: "B_SPORTS", name: "Sports & Fitness Block" },
	{ id: "B_MULTIPURPOSE", name: "Multipurpose Block" },
	{ id: "B_ARYABHATA", name: "Aryabhata Hostel" },
	{ id: "B_BHASKARA", name: "Bhaskara Hostel" },
	{ id: "B_FRESHERS", name: "Freshers Block" },
	{ id: "B_NRI", name: "NRI Block" },
	{ id: "B_ADMIN", name: "Administrative Block" },
	{ id: "B_LIBRARY", name: "Central Library" },
	{ id: "B_HOSTEL_BOYS", name: "Boys Hostel" },
	{ id: "B_HOSTEL_GIRLS", name: "Girls Hostel" },
].sort((a, b) => a.name.localeCompare(b.name));

export const rooms: Room[] = [
	{
		id: "APEX-AUDITORIUM",
		buildingId: "B_APEX",
		roomNumber: "AUD",
		name: "Apex Block Auditorium",
		category: "seminarHall",
		floor: 0,
		anchorNodeId: "N_APEX",
	},
	{
		id: "APEX-BOARDROOM",
		buildingId: "B_APEX",
		roomNumber: "BR-1",
		name: "Apex Board Room",
		category: "boardRoom",
		floor: 1,
		anchorNodeId: "N_APEX",
	},
	{
		id: "ESB-SEMINAR-1",
		buildingId: "B_ESB",
		roomNumber: "SH-1",
		name: "ESB Seminar Hall 1",
		category: "seminarHall",
		floor: 1,
		anchorNodeId: "N_ESB",
	},
	{
		id: "ESB-SEMINAR-2",
		buildingId: "B_ESB",
		roomNumber: "SH-2",
		name: "ESB Seminar Hall 2",
		category: "seminarHall",
		floor: 1,
		anchorNodeId: "N_ESB",
	},
	{
		id: "ESB-BOARDROOM",
		buildingId: "B_ESB",
		roomNumber: "BR-ESB",
		name: "ESB Board Room",
		category: "boardRoom",
		floor: 1,
		anchorNodeId: "N_ESB",
	},
	{
		id: "DES-HITECH-SH",
		buildingId: "B_DES",
		roomNumber: "HT-SH",
		name: "DES Hi-Tech Seminar Hall",
		category: "seminarHall",
		floor: 1,
		anchorNodeId: "N_DES",
	},
	{
		id: "DES-BOARDROOM-1",
		buildingId: "B_DES",
		roomNumber: "BR-1",
		name: "DES Board Room 1",
		category: "boardRoom",
		floor: 1,
		anchorNodeId: "N_DES",
	},
	{
		id: "DES-BOARDROOM-2",
		buildingId: "B_DES",
		roomNumber: "BR-2",
		name: "DES Board Room 2",
		category: "boardRoom",
		floor: 1,
		anchorNodeId: "N_DES",
	},
	{
		id: "LHC-SH-1",
		buildingId: "B_LHC",
		roomNumber: "SH-1",
		name: "LHC Seminar Hall 1",
		category: "seminarHall",
		floor: 1,
		anchorNodeId: "N_LHC",
	},
	{
		id: "LHC-SH-2",
		buildingId: "B_LHC",
		roomNumber: "SH-2",
		name: "LHC Seminar Hall 2",
		category: "seminarHall",
		floor: 1,
		anchorNodeId: "N_LHC",
	},
	{
		id: "LIB-MAIN-READING",
		buildingId: "B_LIBRARY",
		roomNumber: "READING",
		name: "Central Library – Reading Hall",
		category: "library",
		floor: 1,
		anchorNodeId: "N_LIBRARY",
	},
	{
		id: "LIB-STACKS",
		buildingId: "B_LIBRARY",
		roomNumber: "STACKS",
		name: "Central Library - Stacks",
		category: "library",
		floor: 1,
		anchorNodeId: "N_LIBRARY",
	},
	{
		id: "SPORTS-GYM",
		buildingId: "B_SPORTS",
		roomNumber: "GYM",
		name: "Fitness Centre / Gym",
		category: "sports",
		floor: 0,
		anchorNodeId: "N_SPORTS",
	},
	{
		id: "SPORTS-INDOOR-GAMES",
		buildingId: "B_SPORTS",
		roomNumber: "INDOOR",
		name: "Indoor Games Hall",
		category: "sports",
		floor: 0,
		anchorNodeId: "N_SPORTS",
	},
	{
		id: "ADMIN-OFFICE",
		buildingId: "B_ADMIN",
		roomNumber: "G-01",
		name: "Principal's Office / Admin Reception",
		category: "admin",
		floor: 0,
		anchorNodeId: "N_ADMIN",
	},
	{
		id: "ADMIN-PLACEMENT",
		buildingId: "B_ADMIN",
		roomNumber: "P&T",
		name: "Placement & Training Office",
		category: "office",
		floor: 1,
		anchorNodeId: "N_ADMIN",
	},
	{
		id: "MP-CANTEEN",
		buildingId: "B_MULTIPURPOSE",
		roomNumber: "B-01",
		name: "Main Canteen",
		category: "other",
		floor: -1,
		anchorNodeId: "N_MULTIPURPOSE",
	},
	{
		id: "LHC-101",
		buildingId: "B_LHC",
		roomNumber: "101",
		name: "Lecture Hall 101",
		category: "classroom",
		floor: 1,
		anchorNodeId: "N_LHC",
	},
	{
		id: "LHC-102",
		buildingId: "B_LHC",
		roomNumber: "102",
		name: "Lecture Hall 102",
		category: "classroom",
		floor: 1,
		anchorNodeId: "N_LHC",
	},
	{
		id: "ESB-ECE-LAB-1",
		buildingId: "B_ESB",
		roomNumber: "LAB-1",
		name: "ECE Lab 1",
		category: "lab",
		floor: 2,
		anchorNodeId: "N_ESB",
	},
];

export const buildingAnchors: { [key: string]: string } = {
	B_APEX: "N_APEX",
	B_ESB: "N_ESB",
	B_DES: "N_DES",
	B_LHC: "N_LHC",
	B_ARCH: "N_ARCH",
	B_RND: "N_RND",
	B_WORKSHOP: "N_WORKSHOP",
	B_HERITAGE: "N_HERITAGE",
	B_SPORTS: "N_SPORTS",
	B_MULTIPURPOSE: "N_MULTIPURPOSE",
	B_ARYABHATA: "N_ARYABHATA",
	B_BHASKARA: "N_BHASKARA",
	B_FRESHERS: "N_FRESHERS",
	B_NRI: "N_NRI",
	B_ADMIN: "N_ADMIN",
	B_LIBRARY: "N_LIBRARY",
	B_HOSTEL_BOYS: "N_HOSTEL_B",
	B_HOSTEL_GIRLS: "N_HOSTEL_G",
};
